name: CI/CD .NET App Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # change to 8.0 if your project targets .NET 8

    - name: Build and publish
      run: |
        dotnet restore
        dotnet publish -c Release -o out

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/devops-test/devopstest
          git pull origin main
          dotnet publish -c Release -o out
          sudo systemctl restart devopstest
